### ISSUE TITLE
Could you please share the data processing steps for the datasets in the data folder?

### ISSUE THREAD

**Issue by yinpu** [enoche/BM3#1]
Hello, enoche, thank you for sharing your code and datasets. I am very interested in your bm3 experiment and I would like to ask you if you could share the code for the data processing methods for the datasets in the data folder, namely baby, sports, and elec. I am not sure how you transformed the raw data into the format that your code can read. If you provide the code for the data processing methods，I would appreciate it very much. Thank you for your time and help!

**Comment by enoche** [comment]
> Hello, enoche, thank you for sharing your code and datasets. I am very interested in your bm3 experiment and I would like to ask you if you could share the code for the data processing methods for the datasets in the data folder, namely baby, sports, and elec. I am not sure how you transformed the raw data into the format that your code can read. If you provide the code for the data processing methods，I would appreciate it very much. Thank you for your time and help!

Hi, yinpu, thanks for your nice suggestion.
I've updated the [`README`](https://github.com/enoche/BM3/tree/master/data) file in data dir, describing how to preprocess the raw data step by step. 

All scripts will be cleaned and released soon.

**Comment by enoche** [comment]
Hi, @yinpu  I've updated all the preprocessing scripts in the [`preprocessing` dir](https://github.com/enoche/MMRec/tree/master/preprocessing) for your reference. Thanks.

**Comment by 611699** [comment]
你好，数据集的预处理脚本可以分享一下吗？我对你的实验非常感兴趣，目前很想知道你是怎么处理数据集和提取特征的，我的邮箱是：A611799@163.com。非常感谢你的帮助
