### ISSUE TITLE
Missing u_id_mapping.csv and i_id_mapping.csv files for elec and cloth dataset

### ISSUE THREAD

**Issue by rabbicat30** [enoche/BM3#10]
I'm trying to find other auxiliary information from the original dataset through index mapping, but found that the u_id_mapping and i_id_mapping files are missing from both the elec and cloth datasets available on the link provided, can you add these two files or send them to me privately(email: 1527796339@qq.com)? It will help me a lot, appreciate it!

**Comment by enoche** [comment]
Hi, @rabbicat30 sorry for my late response.
I've uploaded the id mapping of Clothing to [Dataset Dir](https://drive.google.com/drive/folders/13cBy1EA_saTUuXxVllKgtfci2A09jyaG?usp=sharing), sorry that the Elec dir is deleted from the server due to disk management.

**Comment by rabbicat30** [comment]
> Hi, @rabbicat30 sorry for my late response. I've uploaded the id mapping of Clothing to [Dataset Dir](https://drive.google.com/drive/folders/13cBy1EA_saTUuXxVllKgtfci2A09jyaG?usp=sharing), sorry that the Elec dir is deleted from the server due to disk management.

Thank you so much!!!

**Comment by enoche** [comment]
You are always welcomed~
