### ISSUE TITLE
bm3文件运行时无法调用common和utils里的python文件和函数

### ISSUE THREAD

**Issue by chying1999** [enoche/BM3#11]
您好，我尝试过创建新的_init_.py，也尝试过在bms.py里添加总路径，但是程序运行的时候还是无法调用common和utils里的文件和函数，想问问怎么解决，谢谢！

**Comment by chying1999** [comment]
也尝试过在bm3.py里通过import sys的方式添加路径

**Comment by enoche** [comment]
请运行 `src/main.py`文件。

**Comment by 611699** [comment]
> 也尝试过在bm3.py里通过import sys的方式添加路径

用VS code打开就没问题，用pycharm则不行
