### ISSUE TITLE
预测时如何应用模态特征

### ISSUE THREAD

**Issue by TangJiakai** [enoche/BM3#3]
论文和代码中并没有看到如何融合多模态特征用于打分，而只使用了ID特征。

**Comment by enoche** [comment]
Hi, 谢谢您的反馈！
对，像您说的一样：在BM3的预测时，只使用了ID特征。因为通过前面的MMCL对比将多模态特征融合到ID特征中了，所以预测的时候不需要多模态特征，这样预测速度上也会更有效！

您的观点很好。其实也可以像我们的[FREEDOM](https://github.com/enoche/FREEDOM)模型一样，在预测时加入多模态的特征，然后作一个　权重调合。您如果有时间可以试试，然后分享一下效果。谢谢！

**Comment by TangJiakai** [comment]
ok，只是感觉有点震惊，毕竟各模态的embedding和权重矩阵都是可训练参数，训了半天最后竟然没用上😂

**Comment by enoche** [comment]
> ok，只是感觉有点震惊，毕竟各模态的embedding和权重矩阵都是可训练参数，训了半天最后竟然没用上😂

也是，哈哈～
模态怎么用在　多模态推荐这边还真是个问题～　您可以重点放在这边研究研究！
