### ISSUE TITLE
方便分享一下运行的环境嘛？

### ISSUE THREAD

**Issue by MathscrG** [enoche/BM3#4]
您好！感谢开源代码，我在复现的时候发现在baby数据集上复现效果差一些，我在想是不是运行的torch等库的版本问题，请问方便分享一下运行环境的配置吗？

**Comment by enoche** [comment]
嗯，我的conda主要packages版本如下，我会马上分享我这边pre-trained好的模型出来，到时候您可以测试：

numpy==1.21.5
pandas==1.3.5
python==3.7.11
scipy==1.7.3
torch==1.11.0
pyyaml==6.0

**Comment by enoche** [comment]
> 

Trained模型及logs在这个目录下: https://github.com/enoche/BM3/tree/master/trained-models-logs

**Comment by MathscrG** [comment]
十分感谢！
