### ISSUE TITLE
result reproduction settings

### ISSUE THREAD

**Issue by weiwei1206** [enoche/BM3#5]
Hello, thanks for sharing the code. Could you report your the specific settings of each datasets for BEST result reproduction? Thanks.
(There are many parameters, but it seems that you only provided a portion of them.)

**Comment by enoche** [comment]
Hi, @weiwei1206  Thanks for your interests in our code.
Pls refer [`README`](https://github.com/enoche/BM3) for the specific settings and trained logs.
