### ISSUE TITLE
Issue on the calculation of time complexity in the Table1

### ISSUE THREAD

**Issue by weiwei1206** [enoche/BM3#6]
Thank you very much for your excellent work. I have some confusion about the calculation of time complexity in your paper.

Can you explain how the time complexity of "Graph Convolution" and "Feature Transform" of GRCN is calculated?

How do you obtain the time complexity of the "Feature Transform" of LATTICE, as shown in Table 1？

**Comment by enoche** [comment]
Hi, @weiwei1206 Thanks for your feedback.
Both "Graph Convolution" and "Feature Transform" are calculated following their published papers or source codes. 
May I know you have any concerns, for detailed analysis on time complexity of an algorithm, pls refer book: [Introduction to Algorithms](https://www.amazon.sg/Introduction-Algorithms-fourth-Thomas-Cormen/dp/026204630X)
