### ISSUE TITLE
How to get image_feature？

### ISSUE THREAD

**Issue by weiwei1206** [enoche/BM3#7]
Thank you for sharing the dataset.
The original dataset only gives the url of the image, how did you get the image? What feature encoder did you use? Or, by "raw dataset", do you mean the dataset that has been processed by previous work?

**Comment by enoche** [comment]
Hi, @weiwei1206 Thanks for your feedback, detailed preprocessing scripts can be obtained at [https://github.com/enoche/MMRec](https://github.com/enoche/MMRec)

> do you mean the dataset that has been processed by previous work?

yes.

Thanks.
